on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./scripts/make-places.js
  schedule:
    - cron: 0 0 * * *
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://docs.google.com/spreadsheets/d/1e7A-maXjmzd0lRcpZpeqjOmfRTZUZMOaxSYQaz_sr8I/gviz/tq?tqx=out:csv&amp;sheet=localities
          downloaded_filename: ./raw-data/localities.csv
          postprocess: ./scripts/make-places.js
